version: 1
default_environment: dev
project_id: 1a07cc3b-f1ae-4547-acbd-37760e64c1ba
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-spreadsheets-anywhere
    variant: ets
    pip_url: git+https://github.com/ets/tap-spreadsheets-anywhere.git
  - name: tap-liti
    inherit_from: tap-spreadsheets-anywhere
    config:
      tables:
      - path: s3://felippe-data
        name: liti_scale
        pattern: raw/liti/.*scale.*csv
        start_date: '2000-01-01T00:00:00Z'
        key_properties:
        - _id
        format: csv
  - name: tap-applehealth
    namespace: tap_applehealth
    pip_url: tap-applehealth
    config:
      file_path: s3://felippe-data/raw/apple-health/export.xml
      stream_maps:
        workouts:
          __alias__: applehealth_workouts
          id: md5(config['hash_seed'] + id)
      stream_map_config:
        hash_seed: 01AWZh7A6DzGm6iJZZ2T
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.6
    config:
      path: 'md:'
      dbname: health
      default_target_schema: raw
jobs:
- name: load-sources-to-duckdb
  tasks:
  - tap-applehealth target-duckdb
  - tap-liti target-duckdb